name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout do código do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --force
        working-directory: ./foodway

      - name: Build frontend
        run: npm run build
        working-directory: ./foodway

      - name: Archive production artifacts
        run: tar -czvf foodway.tar.gz -C ./foodway/dist .
        continue-on-error: true

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use sua chave SSH privada

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "foodway.tar.gz"
          target: "/home/ubuntu/dist"
