name: CI/CD Frontend - Foodway

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Install terraform-docs
        run: |
          curl -Lo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/terraform-docs

      - name: Verify terraform-docs Installation
        run: terraform-docs --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Generate Terraform Documentation
        run: |
          sed -i '/## Terraform Documentation/,$d' README.md
          echo -e "\n## Terraform Documentation\n" >> README.md
          terraform-docs markdown table ./foodway/src/infra >> README.md

      - name: Configure git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Food-Way/Web.git
          git add README.md
          git commit -m "Update Terraform documentation"
          git push

      - name: Terraform Init
        run: terraform init
        working-directory: ./foodway/src/infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./foodway/src/infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./foodway/src/infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./foodway/src/infra