name: CI/CD Frontend - Foodway

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./foodway/src/infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./foodway/src/infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./foodway/src/infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./foodway/src/infra

      - name: Install terraform-docs
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
          tar -xzf terraform-docs-v0.16.0-linux-amd64.tar.gz
          sudo mv terraform-docs /usr/local/bin/

      - name: Render terraform docs
        run: |
          terraform-docs markdown table --config .terraform-docs.yml --output-file README.md --output-mode inject ./foodway/src/infra

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changes
        run: git add README.md

      - name: Commit changes
        run: git commit -m "Update Terraform docs"

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}