name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout do código do repositório

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --force
        working-directory: ./foodway

      - name: Build frontend
        run: npm run build
        working-directory: ./foodway

      - name: Archive production artifacts
        run: tar -czvf foodway.tar.gz -C ./foodway/dist .
        continue-on-error: true

      - name: Copy code to server via SCP FINAL
        run: scp -i ${{ secrets.SERVER_SSH_KEY }} foodway.tar.gz foodway.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/dist

